spring:
    datasource:        
        url: jdbc:postgresql://postgres:5432/fdb
        initialization-mode: always
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
        
